import re

def findMotif(string, substring):
	'''
	Finds the locations of all substrings in the main string
	using regular expression.

	Return: A list of integers
	'''
	l = [m.start()+1 for m in re.finditer('(?=%s)' %(substring), string)]
	s = ''
	for i in l:
		s += str(i) + ' '

	return s



print findMotif('AAACAAGAGGAATGAGGAATGGAGGAATCAGAGGAATCAGAGGAATCGAGGAATGAGGAATCCGAGAGGAATAGAGGAATAATCCGAGGAATCTTCATAAGAGGAATTCGAGAGGAATTTTACAGAGGAATAACAGTAGAGGAATGAGGAATTGAGGAATGAGGAATTAGAGGAATTCGAGGAATTTAGAGGAATACAATTGCGAGGAATCTTGAGGAATGAGGAATGTGAGGAATAGAGGAATAGCGAGGAATTGAGGAATACGAGGAATTAGAGGAATTCAGAGGAATTGAGAGGAATGAGGAATGAGGAATGGAGGAATACTCAGAGGAATTTGCGAGGAATAGGGCGAGGAATGAACCGAGGAATTCTGAGGAATGAGGAATGGAGGAATGGGAGGAATGAGGAATGTTACCTCGAGGAATATGAGAGGAATCGCCGGAGGAATGAGGAATGAGGAATGGGGAGGAATCGAGGAATGAGGAATAGAGGAATGGGGGAGGAATGGAGGAATCTGAGGAATGAGGAATGGAGGAATAACAAAAGAGGAATTAGAGGAATGAGAGGAATGAGGAATGAGGAATGGAGGAATACTTGAGGAATTACCGGAGGAATGAGAGAGGAATGAGGAATCGCTGAGGAATTGAGGAATCCGGTCAGAGAGGAATGAGGAATAAAATGAGGAATAAGAGGAATTTGAGGAATGGTGAGGAATGTTCGGAGGAATCGGAGGAATATAGGAGGAATGAGGAATGAGGAATGAGGAATAGAGGAATCGAGGAATGAGGAATAGAGGAATCGGAGGAATCCAAGAGGAATTCG', 'GAGGAATGA')